# Generated by Django 2.1.3 on 2018-12-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weibo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Liked',
            new_name='Like',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='is_liked',
            new_name='is_like',
        ),
    ]
